[[language]]
name = "rust"
formatter = { command = "rustfmt", args = ["--edition", "2024"] }
auto-format = true

[language-server.rust-analyzer.config]
cargo.features = "all"
check.workspace = false
check.command = "clippy"

[[language]]
name = "lua"
auto-format = true
formatter = { command = "stylua" , args = ["-"] }

[[language]]
name = "yaml"
auto-format = true

[[language]]
name = "protobuf"
language-servers = [ "bufls" ]
