# Author : Jakub Bartodziej <kubabartodziej@gmail.com>
# The theme uses the gruvbox dark palette with standard contrast: github.com/morhetz/gruvbox

"attribute" = "yellow1"

"keyword" ="purple1"
"keyword.directive" = "red1"

"namespace" = "blue1"

"punctuation" = "fg1"
"punctuation.delimiter" = "fg1"

# Operators like &, *, '
"operator" = "orange1"

"special" = "yellow1"

# Variables
"variable" = "fg1"
"variable.builtin" = "orange1"
"variable.parameter" = "fg2"
"variable.other.member" = "fg0"

# Enum
"enum" = "blue1"
"enum.builtin" = "orange1"

# Types
"type" = "fg1"
"type.enum" = "fg1"
"type.parameter" = "fg1"
"type.builtin" = "yellow1"

# Traits
"trait" = "red1"
"trait.builtin" = "yellow1"

# use highlights
"use" = "blue1"
"use.type" = "fg0"
"use.as_clause" = "fg4"
"use.builtin" = "orange0"

"constructor" = "yellow0"

"function" = "blue1"
"function.macro" = "red1"
"function.builtin" = "yellow1"

"tag" = "fg0"

"comment" = { fg = "gray1", modifiers = ["italic"]  }
"comment.block.documentation" = { fg = "cyan1", modifiers = ["italic"]  }

"constant" = "fg0"
"constant.builtin" = "orange1"
"constant.builtin.boolean" = "orange1"

"string" = "green1"

"constant.numeric" = "purple1"
"constant.character.escape" = { fg = "fg2", modifiers = ["bold"] }

"label" = "cyan1"
"module" = "cyan1"

"diff.plus" = "green0"
"diff.delta" = "orange1"
"diff.minus" = "red1"

"warning" = "orange0"
"error" = "red0"
"info" = "cyan0"
"hint" = "blue0"

"ui.background" = { bg = "bg0" }
"ui.linenr" = { fg = "bg4" }
"ui.linenr.selected" = { fg = "yellow1" }
"ui.cursorline" = { bg = "bg1" }
"ui.statusline" = { fg = "fg1", bg = "bg2" }
"ui.statusline.normal" = { fg = "fg1", bg = "bg2" }
"ui.statusline.insert" = { fg = "fg1", bg = "blue0" }
"ui.statusline.select" = { fg = "fg1", bg = "orange0" }
"ui.statusline.inactive" = { fg = "fg4", bg = "bg1" }
"ui.popup" = { bg = "bg1" }
"ui.window" = { bg = "bg1" }
"ui.help" = { bg = "bg1", fg = "fg1" }
"ui.text" = { fg = "fg1" }
"ui.text.focus" = { fg = "fg1" }
"ui.selection" = { bg = "bg2" }
"ui.selection.primary" = { bg = "bg3" }
"ui.cursor.primary" = { bg = "fg4", fg = "bg1" }
"ui.cursor.match" = { bg = "bg3" }
"ui.menu" = { fg = "fg1", bg = "bg2" }
"ui.menu.selected" = { fg = "bg2", bg = "blue1", modifiers = ["bold"] }
"ui.virtual.whitespace" = "bg2"
"ui.virtual.ruler" = { bg = "bg1" }
"ui.virtual.inlay-hint" = { fg = "gray1" }
"ui.virtual.wrap" = { fg = "bg2" }

"diagnostic.warning" = { underline = { color = "orange1", style = "curl" } }
"diagnostic.error" = { underline = { color = "red1", style = "curl" } }
"diagnostic.info" = { underline = { color = "aqua1", style = "curl" } }
"diagnostic.hint" = { underline = { color = "blue1", style = "curl" } }

"markup.heading" = "aqua1"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "green1", modifiers = ["underlined"] }
"markup.link.text" = "red1"
"markup.raw" = "red1"

[palette]
bg0 = "#1d2021" # main background
bg1 = "#3c3836"
bg2 = "#504945"
bg3 = "#665c54"
bg4 = "#7c6f64"

fg0 = "#fbf1c7"
fg1 = "#ebdbb2" # main foreground
fg2 = "#d5c4a1"
fg3 = "#bdae93"
fg4 = "#a89984" # gray0

gray0 = "#a89984"
gray1 = "#928374"

red0 = "#cc241d"
red1 = "#fb4934"
green0 = "#98971a"
green1 = "#b8bb26"
yellow0 = "#d79921"
yellow1 = "#fabd2f"
blue0 = "#458588"
blue1 = "#83a598"
purple0 = "#b16286"
purple1 = "#d3869b"
cyan0 = "#689d6a"
cyan1 = "#8ec07c"
orange0 = "#d65d0e"
orange1 = "#fe8019"
